teamdfir/sift-saltstack

Dockerfile
sift/packages/bulk-extractor.sls
sift/packages/openjdk.sls
sift/repos/docker.sls
sift/repos/gift.sls
sift/repos/openjdk.sls
sift/repos/sift.sls
tests/changed-files.sh
tests/test-state.sh

Fix Bulk Extractor

---

.travis.yml
sift/packages/python-dfvfs.sls
sift/packages/python-plaso.sls
sift/repos/gift.sls
sift/repos/sift.sls
tests/changed-files.sh
tests/packages.sh
tests/test-all.sh
tests/test-state.sh

* plaso 1.4, requires custom python-dfvfs build
* swaps the sift_version to a pillar instead of a grain

set plaso to 1.4,

---

sift/config/folders.sls
sift/config/user/bash-aliases.sls
sift/config/user/bash-rc.sls
sift/config/user/folders.sls
sift/config/user/pdfs.sls
sift/config/user/symlinks.sls
sift/config/user/theme.sls
sift/config/user/user.sls
sift/packages/afterglow.sls
sift/packages/docker-engine.sls
sift/packages/libfvde.sls
sift/packages/python-dfvfs.sls
sift/packages/python-plaso.sls
sift/packages/python-volatility.sls
sift/python-packages/indxparse.sls
sift/repos/docker.sls
sift/repos/gift.sls
sift/repos/sift.sls

Resolves #157 - Addresses an issue where if the hostname or the username selected was SIFT it would create saltstack states with conflicting SLS IDs.

Fix for Issue 157

---

sift/perl-packages/cgi.sls
sift/perl-packages/quicktable.sls
sift/scripts/4n6.sls
sift/scripts/keydet-tools.sls

Added quicktable and cgi perl requirements to perl-packages, added includes for 4n6 scripts to ensure working after install.

4n6 modules

---

sift/packages/default-jre.sls
sift/packages/init.sls
sift/packages/libbcprov-java.sls
sift/packages/libcommons-lang3-java.sls
sift/packages/pdftk-java.sls
sift/packages/pdftk.sls
sift/packages/pdftk_bionic.sls
sift/packages/pdftk_xenial.sls

PDFTK update

---

sift/packages/fdupes.sls
sift/packages/feh.sls
sift/packages/flasm.sls
sift/packages/flex.sls
sift/packages/foremost.sls
sift/packages/g++.sls
sift/packages/gawk.sls
sift/packages/gcc.sls
sift/packages/gdb.sls
sift/packages/gddrescue.sls
sift/packages/ghex.sls
sift/packages/graphviz.sls
sift/packages/grepcidr.sls
sift/packages/gthumb.sls
sift/packages/gzrt.sls
sift/packages/hashdeep.sls
sift/packages/hexedit.sls
sift/packages/htop.sls
sift/packages/hydra-gtk.sls
sift/packages/hydra.sls
sift/packages/ipython3.sls

Updated the package headers F-I

Header updates - packages - F-I

---

sift/desktop.sls
sift/include-desktop.sls
sift/include-server.sls
sift/packages/chromium-browser.sls
sift/packages/init.sls
sift/server.sls

Chromium browser

---

sift/packages/avfs.sls
sift/packages/disktype.sls
sift/packages/init.sls
sift/packages/ntfs-3g.sls
sift/packages/python3-pytsk3.sls
sift/packages/xmount.sls
sift/python3-packages/imagemounter.sls
sift/python3-packages/init.sls

Reviewed issue [#131](https://github.com/teamdfir/sift/issues/131) and found the tool to be useful as well. This update adds a couple of extra packages for support of various partitions / file systems, but most of the requirements are already available in SIFT now.
Resolves https://github.com/teamdfir/sift/issues/131

Add imagemounter (imount) from ralphje

---

sift/python-packages/s2sphere.sls
sift/python3-packages/ijson.sls
sift/scripts/4n6.sls

Fixing the issue with the previous PR

Update 4n6 scripts

---

sift/packages/aws-cli.sls
sift/packages/init.sls

In response to the request for [AWS CLI](https://github.com/teamdfir/sift/issues/572), this will fetch, install, upgrade, and cleanup the AWS CLI.

Add AWS CLI

---

sift/packages/aws-cli.sls

This will update the AWS CLI sha256 hash value.

Update AWS CLI Hash

---

sift/python3-packages/machinae.sls

This PR updates machinae for 24 and adds it to a virtualenv.

Update machinae for 24

---

sift/packages/libicu.sls

Updated for Noble pkg naming. Focal support in this state has not yet been removed.

Update libicu for 24

---

sift/packages/libbz2-dev.sls
sift/packages/zlib1g-dev.sls
sift/python3-packages/init.sls
sift/python3-packages/mac-apt.sls

This PR puts mac-apt back on the list and confirms support for 24, and ensures it's set up in a virtualenv.

Add mac-apt and ensure support for 24

---

sift/packages/dotnet.sls
sift/repos/dotnet-backports.sls
sift/repos/init.sls
sift/scripts/zimmerman.sls

Updated the state to include the dotnet9 sdk requirements and the dotnet9 zimmerman binaries.

Update Zimmerman for 24

---

sift/files/amcache/amcache.py
sift/python3-packages/init.sls
sift/python3-packages/python-registry.sls
sift/scripts/amcache.sls

This adds the amcache script to a virtualenv and removes the python-registry state from python3-packages since it's packages together with the virtualenv in this PR.

Update amcache script for 24

---

sift/scripts/packerid.sls

Updated packerid for 24 with virtualenv and header.

Update packerid for 24

---

sift/scripts/docker-compose.sls

Updates Docker Compose for 24.

Update docker compose for 24

---

sift/files/pdf-tools/mPDF.py
sift/files/pdf-tools/make-pdf-embedded.py
sift/files/pdf-tools/make-pdf-helloworld.py
sift/files/pdf-tools/make-pdf-javascript.py
sift/files/pdf-tools/pdf-parser.py
sift/files/pdf-tools/pdfid.ini
sift/files/pdf-tools/pdfid.py
sift/files/pdf-tools/pdftool.py
sift/files/pdf-tools/plugin_embeddedfile.py
sift/files/pdf-tools/plugin_nameobfuscation.py
sift/files/pdf-tools/plugin_triage.py
sift/scripts/pdf-tools.sls

This PR updates the pdf-tools to all run properly under Python 3 and adds them to a virtualenv.

Update pdf-tools for 24

---

sift/packages/at.sls
sift/packages/init.sls

In response to the pkg request at [Issue 650](https://github.com/teamdfir/sift/issues/650), this will add the linux `at` package.

Add Linux at package
