sift/repos/docker.sls

While attempting to install SIFT on a fresh install of Ubuntu 16.04.02 under VirtualBox 5.1.18 r114002 it was discovered that the keyserver for the docker repo was unavailable.  Specifically this error message is always returned when `sudo salt-call --local --file-root=/tmp/salt state.sls sift` is run:
```
[ERROR   ] Command '['apt-key', 'adv', '--keyserver', 'p80.pool.sks-keyservers.net', '--logger-fd', '1', '--recv-keys', '58118E89F3A912897C070ADBF76221572C52609D']' failed with return code: 2
[ERROR   ] stdout: Executing: /tmp/tmp.7bQXCDbzsA/gpg.1.sh --keyserver
p80.pool.sks-keyservers.net
--logger-fd
1
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: …
```

Correct keyserver path

---

sift/scripts/densityscout.sls

The current source is getting 404, updating the path.

Updating the path of density scout

---

README.md

When 18.04 was added the repo information for 16.04 was copied, including the word 'xenial'. '16.04' was changed to '18.04', but 'xenial' was never updated to 'bionic'. This simply changes that word so that the saltstack apt updates work.

Updated README to correct copy/paste typo

---

sift/scripts/sqlite_miner.sls

This reflects the latest changes from today to let SQLite Miner support how SIFT is trying to call it (as a global, vice from a specific working directory). Most recent SQLite Miner commit is: https://github.com/threeplanetssoftware/sqlite_miner/tree/4220dae48a6e45c1316b153231dc6beef36f2f59
This does *not* yet address the fact that the needed CPAN module DBI is not installed, but at least lets SQLite Miner work if the user installs that manually.

Updated version ot SQLite Miner

---

sift/perl-packages/datecalc.sls
sift/perl-packages/dbi.sls
sift/perl-packages/exiftool.sls
sift/perl-packages/init.sls
sift/perl-packages/json.sls
sift/perl-packages/xpath.sls
sift/scripts/sqlite_miner.sls
sift/server.sls

This branch starts fixing the issues raised in #249 and #263. It adds Perl module support in a method similar to the Python module support, by creating a folder (perl-packages) that has each module inside of it. While this does not use the `cpan.installed` module that saltstack should have, that is because I couldn't get that to work in this environment. Instead this uses the normal Ubuntu package manager to install the modules. 
This will fix the following tools:
- docx-font-extractor.pl XML/XPath.pm
- fb.pl JSON.pm
- ff.pl DBI.pm
- ff_signons.pl DBI.pm
- json-printer.pl JSON.pm
- squirrelgripper.pl DBI.pm, also requires ExifTool
- timediff32.pl Date/Calc.pm
- vmail-db-2-html.pl DBI.pm

Perl Module Support

---

sift/scripts/keydet-tools.sls

The perl modules required for Keydet-tools are already available in the cloned repo in this state. Added the copy command to put them in the required location, and rename the pref.pm to Pref.pm (uppercase P) to ensure these tools function. Requires less overhead than managing the specific files locally.

Copy already downloaded PM's to required location

---

sift/scripts/regripper.sls

Copies the Base.pm, File.pm and Key.pm which are already updated on keydet89 github (and are already cloned with existing state) to the appropriate locations for 2020 date correction.

Copy of required PM files to proper locations for 2020 date fix

---

sift/perl-packages/quicktable.sls

cpan stalls on installation of HTML::QuickTable due to prompt for choices. Added the env variable for the cmd.run "PERL_MM_USE_DEFAULT: 1" to ensure that cpan essentially 'says yes' to the prompts which cause it to stall.

Set CPAN to accept defaults using env variable during quicktable install

---

README.md

The link for the Repo in README.md is broken. Have followed the 16.04 logic and linked to latest, but may need a change to 2019.2 .

Fixed broken repo in README.md

---

sift/scripts/regripper.sls

Even though RegRipper has been updated to 3.0, the regripper.sls state keeps copying the rip.pl file found in sift/files/regripper over to the installation, causing the rip.pl file to remain at the 2008 version. 
Updates to this state will allow for the up-to-date changes made to the RegRipper3.0 repo to remain, without reliance on a specific version of the file in the SIFT repo.
This state will:
- Replace the rip.pl header of C:\perl\bin\perl.exe with /usr/bin/perl
- Assign a static entry to the my $plugindir statement
- Comment out the two following lines for the $plugindir assignment, thus allowing the static assignment to remain.
I will note here that there appears to be an error with the mountdev2 plugin as well regarding an unclosed curly brace and regex. I opted not to fix that …

Fix for regripper issues during update/upgrade

---

sift/files/volatility/pstotal.py
sift/python-packages/openpyxl.sls
sift/python-packages/volatility.sls

Noticed that openpyxl was missing for timeliner output to XLSX. While the latest version is 3.0.5, the volatility renderers only support openpyxl 2.1.2, so I pinned the state to that. It wasn't added to the init.sls as it's only required by Volatility.
Updated the pstotal plugin as recommended by [@Pitteuchar](https://github.com/teamdfir/sift/issues/269#issuecomment-410028231) in Issue [#269](https://github.com/teamdfir/sift/issues/269).

Updated pstotal, requirement for openpyxl

---

sift/packages/init.sls
sift/packages/python3-plaso.sls
sift/packages/python3-redis.sls

Came across [this issue](https://github.com/log2timeline/plaso/issues/3163) with a few fresh installs today (docker, dedicated VM, addon VM). python3-redis and pip3's redis are both getting installed based on requirements, but the pip3 version isn't updating to the latest version (it's sticking to 3.3.11). By pinning to the GIFT version of python3-redis, this will guarantee that python3-plaso has the correct version of redis to continue processing.

Force plaso to bind to python3-redis

---

sift/python-packages/pillow.sls

While pillow will install with the volatility state because it includes the python3-pip, the pillow state alone will not install without the python3-pip binary. 
Added the sift.packages.python3-pip include statement to ensure compatibility with salt.
This pull does not require a new release, as volatility and pillow will install correctly. This is just more for upkeep.

Include python3-pip for salt requirement

---

sift/packages/init.sls

There was a typo in the init for plaso, and the test-nop didn't include the plaso states.

Typo, missing packages in test-nop

---

sift/python3-packages/pillow.sls

SLS ID's in Salt should be unique across states, and unfortunately this ID (sift-python-packages-pillow) exists in both the python2 and python3 version. Updated the python3 state to read sift-python3-packages-pillow.

Salt ID's conflicting

---

sift/python-packages/capstone.sls

Python-capstone is no longer up-to-date with the current python2 capstone, so it was removed in favor of the pip capstone. However, if not removed through APT pkg manager, pip can't install capstone properly.
Modified the state to remove python-capstone first, then install capstone using pip.

Fix capstone installation

---

sift/packages/python2-pip.sls

This will fix the python2 get-pip.py error that popped up in the last few days. It pulls from a specific 2.7 folder at bootstrap.pypa.io, give the root one (which is now configured for Python3).

Update python2-pip to pull from 2.7 folder

---

sift/packages/init.sls
sift/packages/magnus.sls
sift/packages/onboard.sls
sift/packages/orca.sls
sift/repos/flexiondotorg.sls

This will add the three tools recommended by @philhagen in SIFT Issue [#500](https://github.com/teamdfir/sift/issues/500): magnus, orca, and onboard. 
I've configured the state to add the repo for magnus then install the pkg for Ubuntu 18 (to avoid the snap), but for Ubuntu 20 this isn't needed, since magnus is in the apt package listing. This does create a minor versioning gap as installing from the flexiondotorg repo in 18 gives version 1.0.2, but installing from APT in 20 gives 1.0.3.

Added Accessibility tools as per #500

---

sift/python3-packages/argparse.sls
sift/python3-packages/bitstring.sls
sift/python3-packages/colorama.sls
sift/python3-packages/defang.sls
sift/python3-packages/geoip2.sls
sift/python3-packages/ioc_writer.sls
sift/python3-packages/keyrings-alt.sls
sift/python3-packages/lxml.sls
sift/python3-packages/machinae.sls
sift/python3-packages/pillow.sls
sift/python3-packages/pip.sls
sift/python3-packages/pyhindsight.sls
sift/python3-packages/python-dateutil.sls
sift/python3-packages/python-evtx.sls
sift/python3-packages/python-magic.sls
sift/python3-packages/python-registry.sls
sift/python3-packages/setuptools-rust.sls
sift/python3-packages/setuptools.sls
sift/python3-packages/six.sls
sift/python3-packages/stix-validator.sls
sift/python3-packages/stix.sls
sift/python3-packages/upgrade.sls
sift/python3-packages/virustotal-api.sls
sift/python3-packages/wheel.sls
sift/python3-packages/yara-python.sls

There have been a lot of changes in pip over the last few months, some of which cause salt to break with `upgrade: True` [as seen here](https://github.com/saltstack/salt/issues/59100), and now some packages which require cryptography need a newer version of pip along with setuptools_rust to install. 
This pull request first upgrades pip to 21.0.1 in both Bionic and Focal, then installs all the python3 packages, then runs a state called `upgrade.sls` which does a manual upgrade to all python3 packages which previously had `upgrade: True`. It also includes setuptools_rust for pyhindsight, which requires a newer version of pip. Version 21.0.1 of pip is a stable version of pip which accomplishes all tasks on both supported versions of Ubuntu.
The `pip.sls` state accomplishes the pip upgrade …

Fix pyhindsight and python3 packages

---

sift/perl-packages/dbd-sqlite.sls
sift/perl-packages/init.sls
sift/scripts/sqlite_miner.sls

When running sqlite_miner on an sqlite file, it errors out with a statement that it is missing DBD/SQLite.pm
Added the DBD::SQLite state, updated the version of sqlite_miner.pl (pulling now from master), and added a header (without category at this time).

Fix sqlite_miner requirements, update

---

sift/config/user/ssh.sls
sift/config/user/user.sls

This fixes the .ssh issue listed in SIFT Issue [#510](https://github.com/teamdfir/sift/issues/510). Also, in the latest salt 3001, the "gid_from_name" is no longer a valid option, resulting in the following error:
`salt.exceptions.SaltInvocationError: 'gid_from_name' is an invalid keyword argument for 'user.present'`
Updated this to be `usergroup: True` to fix this issue.

Fix for SSH Issue 510

---

sift/packages/python2-pip.sls

The URL for pulling the python2 get-pip.py script has changed. This pull modifies the URL to download from the proper location.

Fix python2 pip install

---

sift/python-packages/pefile.sls

An issue with pefile [here](https://github.com/erocarrera/pefile/issues/318) causes an error during install. A pull request has been submitted with the original source to rectify this issue. However on the off chance this fix isn't applied in a timely manner, I have created a fix for the issue and modified the salt state for pefile to accommodate for the fix.
Once the author fixes the issue with pefile and the error no longer exists, this salt state can be returned to normal.

Temporary fix for pefile issue

---

sift/python-packages/pefile.sls

The author of pefile has decided not to support python2 any further, and has yanked the 2021.5.13 release which was causing the python2 errors. Now, installing pefile via python2 pip reverts to the 2019 version of pefile, which is fully python2 compliant.
Since there is no longer need for redirection to the python2-fixed 2021.5.13 version, I've restored the salt state to its original condition.

Restore pefile

---

sift/python-packages/volatility.sls

Utilizing the same method we used in REMnux to resolve the same issue (originally pulled from [issue #218](https://github.com/teamdfir/sift/issues/218#issuecomment-469860286)), updated the malfind plugin to change the short_options for the plugin to avoid the conflict error.

Fix for malfind yarascan plugin issue 389

---

sift/python-packages/indxparse.sls
sift/python-packages/init.sls

Fixes issue [537](https://github.com/teamdfir/sift/issues/537) where INDXParse is missing. Turns out, it was missing from the init state in python-packages. Also rectified the prepend for focal to use `/usr/bin/env python2` rather than just `python`.
Resolves https://github.com/teamdfir/sift/issues/537

Re-add INDXParse to init

---

sift/python3-packages/init.sls
sift/python3-packages/python3-keyring.sls

This resolves an issue with the KDE Wallet window popping up during python3 package installs. It will change a local environment variable to indicate that the keyring is set to null during the installation, but does not persist so it will not impact existing wallets.

Fix KDE Wallet issue

---

sift/python3-packages/setuptools.sls

Setuptools causes a crash during regular apt updates / upgrades because the semantic versioning of packages doesn't fit standard now enforced by setuptools above 66. Issue referenced [here](https://github.com/pypa/setuptools/issues/3772).
This PR will pin setuptools to any version under 66 until the issue is resolved.

Fix issue with setuptools causing crash

---

sift/python-packages/m2crypto.sls

Due to m2crypto recently dropping support for Python 2 in version 0.41.0, the install of m2crypto to support volatility2 and vshot fails. The last version to support Py2 is 0.40.1, so in order to support volatility2 and vshot, this PR pins the version of m2crypto at 0.40.1.

Update m2crypto version requirement

---

sift/packages/dotnet.sls
sift/repos/microsoft.sls
sift/scripts/init.sls
sift/scripts/zimmerman.sls

As per the request in [Issue 602](https://github.com/teamdfir/sift/issues/602), this modification adds the Zimmerman Tool suite, but only those tools compatible to run in Linux. It also adds the Microsoft repo, to get the dotnet-sdk-6.0 required for the tools.

Add Zimmerman Tools

---

sift/packages/aws-cli.sls
sift/packages/init.sls

With the consistent updating of the aws-cli, this PR will make the installation process static, in that a version can be pinned, and then updated on a more regular interval.

Update aws-cli to be static

---

sift/packages/dotnet.sls
sift/repos/microsoft.sls
sift/scripts/init.sls
sift/scripts/zimmerman.sls

As per the previous PR, this state will allow for the installation of dotnet-sdk-6.0 on SIFT to support Zimmerman tools, however this state will now download each zip independently instead of as one group. The previous PR pulled a single zip file which no longer exists at its previous path, thus the update to this state.
It will also install dotnet based on the OS version at time of install. On Focal, the dotnet-sdk-6.0 does not exist without the support of the Microsoft repo, but it does exist on Jammy without the repo. If installing on Jammy with the repo, the installation completes but does not function as intended (see error [identified here](https://github.com/dotnet/core/issues/5746)).

Update Zimmerman Tools installation

---

sift/python3-packages/defang.sls

This PR updates defang with a virtualenv and symlink vice a standard pip install. It removes sift.python3-packages.pip because it is not required with virtualenv.

Update defang with virtualenv

---

sift/packages/bless.sls

`bless` is not available in Noble, so this adds a test case for the oscodename and if `noble`, then it will ignore the state and continue. Added a `TODO: fix` statement in the header as well.

Update bless for 24

---

sift/packages/cryptcat.sls

Cryptcat is not in Noble, so I've added a test case and a `test.nop` as well as a TODO: fix.

Update cryptcat for 24

---

sift/packages/libncurses.sls

The libncurses5-dev pkg is transitionally named that for transition to libncurses-dev in both Jammy and Noble. As such, the libncurses5-dev pkg does not exist in noble, but is named libncurses-dev (as it also is in jammy). Modified the state to reflect the proper package name.

Update libncurses for 24

---

sift/packages/netcat.sls

The `netcat` pkg from Jammy and Focal is actually a transitional package for `netcat-openbsd` (which is also available in Jammy under this name), and subsequently installs that pkg. Since the `netcat` package itself isn't available in Noble, and is actually now just `netcat-openbsd` (which works in both Jammy and Noble), this PR updates the state to explicitly call the package as `netcat-openbsd`.
This PR also adds a header to the state.

Update netcat for 24

---

sift/packages/qemu.sls

The `qemu` package previously installed was a `dummy package` and not the actual qemu package:
```bash
qemu/jammy-updates,jammy-security 1:6.2+dfsg-2ubuntu6.24 amd64
fast processor emulator, dummy package
```
It only previously installed a 14kb placeholder and not qemu.
The actual package is now called `qemu-system` and is available in both Jammy and Noble. This PR updates the package name and adds a header.

Update qemu for 24

---

sift/packages/libafflib-dev.sls
sift/packages/libafflib.sls

libafflib has two different versions, one in each of noble and jammy. This PR updates the logic for testing the oscodename, and applies the new version. I've also updated the headers for both the libafflib and libafflib-dev states.

Update libafflib for 24

---

sift/packages/powershell.sls

Previous powershell version 7.4.1 could not be installed in Noble due to it requiring a lower version of libicu than was available in Noble. This state updates the version to 7.4.6 which will install and run on Noble and the available version of libicu.
The libicu state has already been updated in #141 to reflect this requirement.

Update PowerShell for 24

---

sift/packages/libext2fs2.sls

This PR adds a header for libext2fs2 and adds logic for testing oscodename and applying the appropriate package based on the logic.

Update libext2fs2 for 24

---

sift/packages/libpff-dev.sls
sift/packages/libpff-tools.sls
sift/packages/libpff.sls
sift/packages/pff-tools.sls
sift/packages/python3-pypff.sls

libpff1 has a different name in noble, so this PR updates the test logic for the oscodename and installs the appropriately named pkg. This PR also adds headers for the related pff states (libpff-dev, pff-tools, python3-pypff) and removes the old / unused libpff-tools state which did the same thing as the pff-tools state.

Update libpff states for 24

---

sift/scripts/regripper.sls

Regripper state only needed a minor change due to some modifications made at the tail-end of 2024.

Update regripper for 24

---

sift/packages/file.sls
sift/packages/init.sls
sift/packages/libbde-tools.sls
sift/packages/libbde-utils.sls
sift/packages/libbde.sls
sift/packages/libewf-dev.sls
sift/packages/libewf-tools.sls
sift/packages/libewf2.sls
sift/packages/libvhdi.sls
sift/packages/lvm2.sls
sift/packages/mdadm.sls
sift/packages/python3-pytsk3.sls
sift/packages/python3-tsk.sls
sift/python3-packages/imagemounter.sls
sift/python3-packages/init.sls

This PR will fix an issue with the installation of imagemounter due to conflicts with available packages. It also updates multiple packages to use the `GIFT` repo to install these packages, as they are more up-to-date than the available versions from each distro's `APT` repository.

Fix an issue with imagemounter installation

---

sift/python3-packages/indxparse.sls
sift/scripts/4n6.sls

The scripts state and INDXParse state fail due to an issue with packaging being less than it needs to be for the install to complete successfully in Jammy.

Update INDXParse and scripts venv packages

---

sift/python3-packages/python-evtx.sls

The most recent version of python-evtx (0.8.1) has introduced a `pyproject.toml` installation method vice the `setup.py` installation method. At the current time, this method does not correctly install the scripts in the appropriate location, causing them to fail on execution ([more information can be found here](https://github.com/williballenthin/python-evtx/issues/94)).
To account for this, the most recent version of python-evtx which does not have this version (0.8.0) is being used in this PR, and being pinned to that commit specifically, until such time as the installation method is updated to address the issue referenced above.

Fix Issue 663
